# Generated by Django 4.0.4 on 2022-08-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('vin', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('number_seats', models.IntegerField()),
                ('category_fk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusApp.category')),
            ],
            options={
                'db_table': 'BusDetails',
            },
        ),
    ]
