# Generated by Django 4.0.4 on 2022-08-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busdetails',
            old_name='category_fk_id',
            new_name='category',
        ),
    ]
