# Generated by Django 4.0.4 on 2022-08-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0002_rename_category_fk_id_busdetails_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='craeted_by',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='created_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='modified_by',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='modified_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='craeted_by',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='created_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='modified_by',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='modified_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
