# Generated by Django 4.0.4 on 2022-08-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0003_busdetails_craeted_by_busdetails_created_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busdetails',
            old_name='craeted_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='craeted_by',
            new_name='created_by',
        ),
    ]
